# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  authenticationserviceapi:
    image: authenticationserviceapi
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5197:5197
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
